### PR TITLE
Reorganise tests

### LINKED ISSUE #48: Tests can be reorganised
Currently, the filenames for tests are not descriptive, and tests are copied and pasted, whereas they could be run in a loop using 1 function

@2sn FYI - `pytest` will look for files starting with `test_`, and will run all functions in these files with names starting with `test_`. So it's okay to group all of the tests together by having several functions in one file. And for tests that follow the same format, you can have a list of arguments.

### PR DESCRIPTION
**Pull request by conradtchan**
Since all the single star fit tests are the same (except for the filename and answer), they can be grouped together.
Resolves #48

### CODE REVIEW

**Comment by 2sn** [comment]
@conradtchan it was also very much intended to have the test be executed in specific order, which is why I added the numbers in the first place.  The reason was to have the single star test first, because they run very fast.  One could immediately see what was tested and failed.  I think I would not want to wait for the 20 s GA test to comeple to then see the 10 ms single star test fail.

**Comment by 2sn** [comment]
@conradtchan from the way it is written now, from the loop it is not clear which of the single star data tests failed, or is it? at least when I look at the logs on github.  This would be rather useful.

**Comment by 2sn** [comment]
@conradtchan thanks for showing the technique, but I think I prefer the previous version because of clarity and preferred execution order.  (Or, can one configure pytest to execute tests in a specific order other then alphabetic?)

**Comment by conradtchan** [comment]
@2sn 

>  preferred execution order.

Understood - I've added the numerical ordering back in.

> can one configure pytest to execute tests in a specific order other then alphabetic?

This is possible using [pytest-ordering](https://pytest-ordering.readthedocs.io/en/develop/) but is a little bit overkill for now.

> it is not clear which of the single star data tests failed

When the tests pass, they do not show which one has passed. But when they fail, pytest outputs the captured logs from the failed test and shows which parameters caused the test failed. The parameters within a given test are run in the order that you provide them. You can try this locally by manually altering the expected value to an incorrect value. For example, I set
```
("BD_80_245.dat", 10.12390641724435)
```

and this was the test output:
```
❯ pytest
================================================= test session starts ==================================================
platform darwin -- Python 3.10.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/conrad/repos/starfit
collected 9 items

tests/test_double.py .                                                                                           [ 11%]
tests/test_ga.py .                                                                                               [ 22%]
tests/test_single.py ..F....                                                                                     [100%]

======================================================= FAILURES =======================================================
________________________________________ test[BD_80_245.dat-10.12390641724435] _________________________________________

filename = 'BD_80_245.dat', expected = 10.12390641724435

    @pytest.mark.parametrize("filename, expected", testdata)
    def test(filename, expected):
        """Test single star fits"""

        test_result = starfit.Single(filename, silent=True).sorted_fitness[0]

>       assert np.isclose(test_result, expected)
E       assert False
E        +  where False = <function isclose at 0x1073e1480>(1.12390641724435, 10.12390641724435)
E        +    where <function isclose at 0x1073e1480> = np.isclose

tests/test_single.py:23: AssertionError
-------------------------------------------------- Captured log call ---------------------------------------------------
INFO     BBNAbu:logged.py:546 Loading /Users/conrad/opt/miniconda3/envs/starfit/lib/python3.10/site-packages/starfit/data/ref/bbnc19.dat (39 kiB)
INFO     BBNAbu:logged.py:455  21 isotopes loaded in 6.1 ms.
INFO     Star:logged.py:546 Loading /Users/conrad/opt/miniconda3/envs/starfit/lib/python3.10/site-packages/starfit/data/stars/BD_80_245.dat (2.9 kiB)
WARNING  SolAbu:abusets.py:123 using default path /Users/conrad/opt/miniconda3/envs/starfit/lib/python3.10/site-packages/starfit/autils/../data/ref
INFO     SolAbu:logged.py:546 Loading /Users/conrad/opt/miniconda3/envs/starfit/lib/python3.10/site-packages/starfit/autils/../data/ref/sollo20.dat (9.1 kiB)
INFO     SolAbu:logged.py:455 287 isotopes loaded in 73 ms.
INFO     Star:logged.py:455  Star loaded and converted in 114 ms.
INFO     Star:read.py:280 Adding BBN upper limits of H and He into star data if missing
INFO     StarDB:stardb.py:529 Loading /Users/conrad/opt/miniconda3/envs/starfit/lib/python3.10/site-packages/starfit/data/db/znuc2012.S4.star.el.y.stardb.gz
INFO     StarDB:stardb.py:533 File size: 12 MiB (compressed).
INFO     StarDB:stardb.py:302 Not swapping endian.
INFO     StarDB:stardb.py:850 file integrity seems OK
INFO     StarDB:stardb.py:1000 Data version:  10100
INFO     StarDB:stardb.py:1001 data set name: znucS4.mixlib.el
INFO     StarDB:stardb.py:1003 ==========================================================
INFO     StarDB:stardb.py:1005 COMMENT: znuc S=4 star data set
INFO     StarDB:stardb.py:1006 ==========================================================
INFO     StarDB:stardb.py:1008 data sets:       17640
INFO     StarDB:stardb.py:1009 abundance sets:     83
INFO     StarDB:stardb.py:1010 ----------------------------------------------------------
INFO     StarDB:stardb.py:1011 abundance type:  2 - element
INFO     StarDB:stardb.py:1016 abundance class: 2 - dec (stable subset of radiso)
INFO     StarDB:stardb.py:1022 abundance unit:  4 - mol fraction (YPS)
INFO     StarDB:stardb.py:1027 abundance total: 1 - ejecta
INFO     StarDB:stardb.py:1036 abundance norm:      (NONE)
INFO     StarDB:stardb.py:1037 abundance data:  0 - all ejecta (SN ejecta + wind)
INFO     StarDB:stardb.py:1042 abundance sum:   1 - number fraction
INFO     StarDB:stardb.py:1048 ----------------------------------------------------------
INFO     StarDB:stardb.py:1049 4 data fields:
INFO     StarDB:stardb.py:1066 mass    [    solar masses] (DOUBLE) <parameter>
INFO     StarDB:stardb.py:1066 energy  [               B] (DOUBLE) <parameter>
INFO     StarDB:stardb.py:1066 mixing  [He core fraction] (DOUBLE) <parameter>
INFO     StarDB:stardb.py:1066 remnant [           M_sun] (DOUBLE) <property>
INFO     StarDB:stardb.py:1087 ----------------------------------------------------------
INFO     StarDB:stardb.py:1088 ABUNDANCES:
INFO     StarDB:stardb.py:1092 H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca
INFO     StarDB:stardb.py:1092 Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb
INFO     StarDB:stardb.py:1092 Sr Y Zr Nb Mo Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs
INFO     StarDB:stardb.py:1092 Ba La Ce Pr Nd Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta
INFO     StarDB:stardb.py:1092 W Re Os Ir Pt Au Hg Tl Pb Bi Th U
INFO     StarDB:stardb.py:1097 ----------------------------------------------------------
INFO     StarDB:stardb.py:1098 PARAMETER RANGES:
INFO     StarDB:stardb.py:1113 mass:         9.6 ...   100.0 (126 values)
INFO     StarDB:stardb.py:1113 energy:       0.3 ...    10.0 ( 10 values)
INFO     StarDB:stardb.py:1113 mixing:   0.00000 ... 0.25119 ( 14 values)
INFO     StarDB:stardb.py:1117 ----------------------------------------------------------
INFO     StarDB:stardb.py:1118 PROPERTY RANGES:
INFO     StarDB:stardb.py:1133 remnant:    1.195 ...  52.949 (941 values)
INFO     StarDB:stardb.py:1136 ----------------------------------------------------------
INFO     StarDB:stardb.py:1137 PARAMETER VALUES:
INFO     StarDB:stardb.py:1139 mass:
INFO     StarDB:stardb.py:1145    9.6   9.7   9.8   9.9  10.0  10.1  10.2  10.3  10.4
INFO     StarDB:stardb.py:1145   10.5  10.6  10.7  10.8  10.9  11.0  11.1  11.2  11.3
INFO     StarDB:stardb.py:1145   11.4  11.5  11.6  11.7  11.8  11.9  12.0  12.2  12.4
INFO     StarDB:stardb.py:1145   12.6  12.8  13.0  13.2  13.4  13.6  13.8  14.0  14.2
INFO     StarDB:stardb.py:1145   14.4  14.6  14.8  15.0  15.2  15.4  15.6  15.8  16.0
INFO     StarDB:stardb.py:1145   16.2  16.4  16.6  16.8  17.0  17.1  17.2  17.3  17.4
INFO     StarDB:stardb.py:1145   17.5  17.6  17.7  17.8  17.9  18.0  18.1  18.2  18.3
INFO     StarDB:stardb.py:1145   18.4  18.5  18.6  18.7  18.8  18.9  19.0  19.2  19.4
INFO     StarDB:stardb.py:1145   19.6  19.8  20.0  20.5  21.0  21.5  22.0  22.5  23.0
INFO     StarDB:stardb.py:1145   23.5  24.0  24.5  25.0  25.5  26.0  26.5  27.0  27.5
INFO     StarDB:stardb.py:1145   28.0  28.5  29.0  29.5  30.0  30.5  31.0  31.5  32.0
INFO     StarDB:stardb.py:1145   32.5  33.0  33.5  34.0  34.5  35.0  36.0  37.0  38.0
INFO     StarDB:stardb.py:1145   39.0  40.0  41.0  42.0  43.0  44.0  45.0  50.0  55.0
INFO     StarDB:stardb.py:1148   60.0  65.0  70.0  75.0  80.0  85.0  90.0  95.0 100.0
INFO     StarDB:stardb.py:1139 energy:
INFO     StarDB:stardb.py:1148   0.3  0.6  0.9  1.2  1.5  1.8  2.4  3.0  5.0 10.0
INFO     StarDB:stardb.py:1139 mixing:
INFO     StarDB:stardb.py:1145  0.00000 0.00100 0.00158 0.00251 0.00398 0.00631 0.01000
INFO     StarDB:stardb.py:1148  0.01585 0.02512 0.03981 0.06310 0.10000 0.15849 0.25119
INFO     StarDB:stardb.py:1152 ----------------------------------------------------------
INFO     StarDB:stardb.py:1153 PROPERTY VALUES:
INFO     StarDB:stardb.py:1155 remnant:
INFO     StarDB:stardb.py:1157 (more than 100 values)
INFO     StarDB:stardb.py:1168 ----------------------------------------------------------
INFO     StarDB:stardb.py:1175 SHA1: 40e59b41fdc4c68dd236d3a1855aaa2ff1489a17
INFO     StarDB:stardb.py:1176 ----------------------------------------------------------
INFO     StarDB:logged.py:455 Data loaded in 65 ms.
INFO     SolAbu:logged.py:546 Loading /Users/conrad/opt/miniconda3/envs/starfit/lib/python3.10/site-packages/starfit/data/ref/sollo22.dat (11 kiB)
INFO     SolAbu:logged.py:455 287 isotopes loaded in 57 ms.
INFO     Single:starfit.py:296 Matching 19 data points from Z=1 to Z=30:
INFO     Single:starfit.py:300     H He O Na Mg Al Si K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn
INFO     Single:starfit.py:302 with 4 upper limits in the data:
INFO     Single:starfit.py:305     H He O Cu
INFO     Single:starfit.py:310 and 0 lower limits in the models:
INFO     Single:starfit.py:312
INFO     Single:fit.py:65 Calculation time:
INFO     Single:fit.py:66  29 ms
INFO     Single:fit.py:74 Best solution:
INFO     Single:fit.py:75  (10092, 0.03465805)
INFO     Single:fit.py:76 Fitness:
INFO     Single:fit.py:77  1.12390641724435
INFO     Single:logged.py:455 Finished in 323 ms.
=============================================== short test summary info ================================================
FAILED tests/test_single.py::test[BD_80_245.dat-10.12390641724435] - assert False
============================================= 1 failed, 8 passed in 24.71s =============================================
```

**Comment by 2sn** [comment]
@conradtchan OK, thanks!

**Review by 2sn — COMMENTED** [review]
all good

**Pull request merged**
