### PR TITLE
code refactor, adjust Direct to multi-db, update doc

### PR DESCRIPTION
**Pull request by 2sn**

### CODE REVIEW

**Comment by 2sn** [comment]
@conradtchan Are you OK with this restructuring?

**Comment by 2sn** [comment]
@conradtchan Also, I had the impression the file `abu_proc.py` was not actually needed for anything.  Can it be removed?

I think it was there to test element combination, but this is now done more elegantly in the main code.

**Review by conradtchan — APPROVED** [review]
Thanks for doing this refactor. The looks much better now. Yes, I think it's fine to remove `abu_proc.py` because you've implemented that functionality into the main code.

I've just added a few spelling fixes. All of them cosmetic, except for the variable `partition` in `multi.py` was misspelt, which could cause some strange behaviour.

**Comment by 2sn** [comment]
@conradtchan Thanks for fixing all the typos.  Especially in all the `autils` modules.  I may have though `functionallity` may have been the American spelling, but maybe that is not a valid excuse.  Nowadays I argue more that the keyboard just has the keys in the wrong place rather than my actual poor spelling.

Thanks for catching the typo on `partition`.  I should have used a better word, but that is what came to mind.  Also, for GA, I ma not quite happy with the `cover` keyword, but nothing better came to mind by the time I implemented it.

I think the key ting to achieve before moving to release 1.0 is to still remove the autils, move the few things that are actually used by `StarFit` itself to the utils section and have the others embedded in there respective packages on PyPI when they get there.

I make one more test release, deploy to `starfit.xyz` (on its fix branch), and then merge when all is OK.

**Comment by conradtchan** [comment]
@2sn No problem! I use [codespell](https://github.com/codespell-project/codespell) to check the spelling. It's even possible to set that up as a pre-commit hook, but I find that causes more frustration than it's worth.

I think your variable names are fine. It wasn't immediately clear to me what they did at first, but you've documented it well enough.

**Comment by 2sn** [comment]
@conradtchan If you have any suggestions for better names, that would be most welcome.  I am not too happy about them; I have the idea in mind but lack the word for it.

**Comment by conradtchan** [comment]
@2sn perhaps `try_all` or `try_all_models`? less elegant, but slightly more descriptive.

**Comment by 2sn** [comment]
@conradtchan I think it is still not quite it, because if `db_n > sol_size` not all can be covered.  It tries to cover as many DBs as possible.  Never mind, no worries.  Some day, a good word may pop up ;-)

**Pull request merged**
