### PR TITLE
Build fortran code as static library

### PR DESCRIPTION
**Pull request by conradtchan**
This PR allows code that is not f2py-compliant to be compiled into a python module.

First, build the Fortran code as a static library. Then generate the f2py wrapper using only an interface fortran file. Finally, build the python module.

Tests:
- Successfully compiles OpenMP code. OpenMP flags are now set by default, though there is no OpenMP code yet
- Using a derived type in the library works as expected, and using a derived type in the interface results in an error as expected

### CODE REVIEW

**Comment by 2sn** [comment]
@conradtchan This now works with the build process?  That would be fantastic!

**Comment by conradtchan** [comment]
@2sn Yes! 😀

I also tested it by adding a derived type in the interface file (which causes an error) and into the library (which works as expected).

**Comment by 2sn** [comment]
Excellent.  This will make thing much better, w/o the need to maintain the `pyf` files

**Comment by 2sn** [comment]
Probably this framework should be contributed to `NumPy` for their builds or as a recipe independently ...

**Comment by 2sn** [comment]
(it also allows me to now move other projects that rely on this - such as Kepler - much easier than it was before (or, at all, that is).

**Comment by 2sn** [comment]
(Maybe in the future you can have Phantom as a Python package as well.)

**Comment by conradtchan** [comment]
It took me some time to figure out, but in the end, it was almost trivial to implement. The key line is:
```
static_library(module_name, fortran_library_sources, dependencies: omp)
```

**Comment by 2sn** [comment]
@conradtchan let me test at home on M1 and Linux.

**Comment by 2sn** [comment]
@conradtchan I find on both M1 and Linux, that during the install a file `. mesonpy-native-file.ini` is generated that contains a link to the python executable
```
[binaries]
python = '/home/alex/Python/bin/python3.11'
```
and
```

[binaries]
python = '/opt/homebrew/Cellar/python@3.11/3.11.2_1/bin/python3.11'
```
I assume this should be added to the `.gitignore` list.

**Comment by 2sn** [comment]
we will no longer need these instructions>
```
# Set environment variable to allow for editable installs
export SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
```

**Comment by 2sn** [comment]
This seems to be a change that it now automatically runs pre-commit when I commit code.

**Comment by 2sn** [comment]
Otherwise, the installation complete w/o error message on both Linux and M1/MacOS 13.2.

**Comment by 2sn** [comment]
Currently, there is still a Makefile, e.g., in `starfit/src/starfit/fitness`.  This was used to build an executable for testing (and testing archiver to build a library).  Could that be ported to meson as well?  And how would that be called / executed instead of `make xxx` ?

**Comment by 2sn** [comment]
(@conradtchan - I promised you as soon as I start looking at things, new questions will arise.)

**Comment by conradtchan** [comment]
> we will no longer need these instructions?
> 
> ```
> # Set environment variable to allow for editable installs
> export SETUPTOOLS_ENABLE_FEATURES="legacy-editable"
> ```

I think this is more relevant for #214, but yes, we can remove those lines from the docs.

**Comment by conradtchan** [comment]
> This seems to be a change that it now automatically runs pre-commit when I commit code.

Did you previously not have pre-commit installed? It should run whenever you commit, that behaviour shouldn't have changed.

**Comment by conradtchan** [comment]
> Currently, there is still a Makefile, e.g., in `starfit/src/starfit/fitness`. This was used to build an executable for testing (and testing archiver to build a library). Could that be ported to meson as well? And how would that be called / executed instead of `make xxx` ?

I can implement this in a new PR, because ideally we need to wait for #214 to be merged in first.

**Pull request merged**
