### PR TITLE
initial updates on autil modules to fix stardb import of newer DBs

### PR DESCRIPTION
**Pull request by 2sn**
replace most of autils

add `nice` to Double (and fix in doc)

some refactor of fit.oy and starfit.py to adjust to new autils, in particular use isotope.ion as I.

### CODE REVIEW

**Comment by 2sn** [comment]
I don't understand the origin of the error message

**Comment by 2sn** [comment]
@conradtchan I don't understand the origin of the error message

**Comment by conradtchan** [comment]
@2sn running pytest locally gave a more useful error message:
```
ImportError while importing test module '/Users/conrad/repos/starfit/tests/test_single.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../opt/miniconda3/envs/starfit/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_single.py:3: in <module>
    import starfit
src/starfit/__init__.py:6: in <module>
    from .fit import Direct, Double, Single
src/starfit/fit.py:12: in <module>
    from .autils.human import time2human
src/starfit/autils/__init__.py:1: in <module>
    from . import abusets, isotope, logged, stardb
src/starfit/autils/abusets.py:19: in <module>
    from .abumodel import AbuModel
src/starfit/autils/abumodel.py:9: in <module>
    from .abuset import AbuSet, IonList
src/starfit/autils/abuset.py:21: in <module>
    from .human import version2human
src/starfit/autils/human/__init__.py:14: in <module>
    import human.config
E   ModuleNotFoundError: No module named 'human'
```
It looks like the imports are not resolving correctly. I think it needs to be changed to `from . import config`. It may be working on your local machine because you have some other packages installed, or other directories in your `PYTHONPATH` so it could be resolving to those instead.

**Comment by 2sn** [comment]
@conradtchan I think this github stuff does not work well,  I dies not run new tests on recent submit.  It seems pretty broken.

**Comment by 2sn** [comment]
local checks are all OK.
```
check for merge conflicts................................................Passed
check yaml...........................................(no files to check)Skipped
detect private key.......................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check that executables have shebangs.................(no files to check)Skipped
check for broken symlinks............................(no files to check)Skipped
black................................................(no files to check)Skipped
isort................................................(no files to check)Skipped
flynt................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
[autils-update-20221011 b1d4201] phony submit
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by 2sn** [comment]
@conradtchan test seem to be not running - expecting outputs ..

**Comment by 2sn** [comment]
@conradtchan I can't determine why this is not working.  I have a feeling github is just broken and should be removed.

**Comment by 2sn** [comment]
I think when monopoly strikes then service suffers.

**Comment by 2sn** [comment]
it also seems that all this beautiful refactoring of code made things now broken that used to work before.
...

File ~/python/starfit/src/starfit/autils/human/__init__.py:34, in __getattr__(name)
     32 if name in _map:
     33     if isinstance(_map[name], str):
---> 34         h = Human(getattr(config, _map[name]))
     35         _map[name] = h
     36     else:

File ~/python/starfit/src/starfit/autils/human/template.py:218, in Human.__init__(self, config, **kwargs)
    216 self.ranges = dict()
    217 ranges_key = (self.digits, self.dec_lim)
--> 218 self.ranges[ranges_key] = self._compute_ranges(self.digits, self.dec_lim)

File ~/python/starfit/src/starfit/autils/human/template.py:265, in Human._compute_ranges(self, digits, dec_lim)
    263 prefix = Prefix.neutral
    264 exponent = False
--> 265 ranges.append(Range(lim, unit, prefix, exponent))
    266 unit_ = unit
    267 lim = unit.value * div_lim(scale)

File ~/python/source/human/range.py:102, in Range.__init__(self, *args, **kwargs)
    100 if stop is None:
    101     stop = +inf
--> 102 if start > stop:
    103     stop, start = start, stop
    104 self._start = start

TypeError: '>' not supported between instances of 'float' and 'Unit'
```

You probably should not allow software to touch your code.

**Comment by 2sn** [comment]
any changes i do to the code are irrelevant, it just wants to fail w/o giving details.

**Comment by 2sn** [comment]
I think they are ignored.

**Comment by 2sn** [comment]
@dliptai so we can delete the branch?

**Comment by dliptai** [comment]
> @dliptai so we can delete the branch?

yes

**Pull request merged**
